#!/bin/bash

echo "🔧 Correction du cache favicon MySecurePassword..."

echo ""
echo "🚀 Étapes à suivre :"
echo ""
echo "1. 📱 Fermer COMPLÈTEMENT Safari/Chrome/Firefox"
echo "   - Quitter l'application (pas juste fermer l'onglet)"
echo ""
echo "2. 🗑️  Vider le cache navigateur :"
echo "   - Chrome : Paramètres > Confidentialité > Effacer données navigation"
echo "   - Safari : Développement > Vider les caches (ou Safari > Préférences > Confidentialité > Gérer données site web)"
echo "   - Firefox : Paramètres > Confidentialité > Effacer données"
echo ""
echo "3. 🔄 Redémarrer le serveur :"
echo "   - Arrêter le serveur (Ctrl+C)"
echo "   - npm run dev"
echo ""
echo "4. ✅ Tester :"
echo "   - Ouvrir http://localhost:3001 dans un NOUVEL onglet"
echo "   - Ou utiliser mode navigation privée"
echo ""
echo "🎯 URLs à tester :"
echo "- http://localhost:3001/"
echo "- http://localhost:3001/favicon.png"
echo "- http://localhost:3001/favicon.ico"
echo ""
echo "💡 Astuce : Le favicon peut prendre 30-60 secondes à apparaître"
echo "            même après avoir vidé le cache."
echo ""